CREATE DATABASE |SQL_BASE_NAME|;
USE |SQL_BASE_NAME|;
 DROP TABLE IF EXISTS `users`;
 CREATE TABLE `users`(
     `id` BIGINT UNSIGNED PRIMARY KEY,
     `name` VARCHAR(40) DEFAULT 'NULL',
     `country` CHAR(2) DEFAULT ''
 ) ENGINE=InnoDB;